spring:
  application:
    name: type-microservice
  datasource:
    url: 'jdbc:h2:mem:typedb'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
  eureka:
    client:
      service-url:
        defaultZone: 'http://localhost:8761/eureka/'

server:
  port: 7070
management:
  endpoints:
    web:
      exposure:
        include: '*'