services:
  mysqldb :
    image: mysql
    container_name: mysqldb
    healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
  departments-ms:
    build: ./type-microservice
    container_name: types-ms
    ports:
      - "7070:7070"
    environment:
       SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/test"
       SPRING_DATASOURCE_USERNAME: root
       SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysqldb :
        condition: service_healthy