server:
  port: 7071
spring:
  application:
    name: client
  datasource:
    url: 'jdbc:h2:mem:clientsdb'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
    ddl-auto: update
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
