spring:
  profiles:
    active: "prod"
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  application:
    name: type-microservice
  datasource:
    url: 'jdbc:h2:mem:typedb'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
server:
  port: 7070

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

build:
  version: "1.0"
