server:
    port: 7073

spring:
    application:
        name: gatewayserver
    cloud:
        config:
            enabled: false
        discovery:
            enabled: true
        gateway:
            routes:
                - id: r1
                  uri: lb://TYPE-MICROSERVICE
                  predicates:
                      - Path=/api/types/**
                - id: r2
                  uri: lb://CLIENT
                  predicates:
                      - Path=/api/clients/**
            discovery:
                locator:
                    enabled: false

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
    instance:
        prefer-ip-address: true

management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        gateway:
            access: unrestricted
