server:
  port: 7071

spring:
  application:
    name: client
  datasource:
    url: 'jdbc:h2:mem:clientsdb'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: '*'
